# ohCHA_RigManager/01/src/utils/translator.py
# Description: [v21.56] TRANSLATION FIXED.
#              - ADDED: Missing keys ('view_label', 'search_ph') for Bone Explorer.

class Translator:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(Translator, cls).__new__(cls)
        return cls._instance

    def __init__(self):
        self.current_lang = "en"
        self.reload_dictionary()

    def reload_dictionary(self):
        self.translations = {
            # ========================================================
            # [0] Sidebar Tabs
            # ========================================================
            "tab_edit_mesh": {"en": "Edit Mesh", "kr": "메시 정리", "jp": "メッシュ編集", "cn": "网格编辑"},
            "tab_rigging": {"en": "Rigging", "kr": "리깅", "jp": "リギング", "cn": "绑定"},
            "tab_skinning": {"en": "Skinning", "kr": "스키닝", "jp": "スキニング", "cn": "蒙皮"},
            "tab_layers": {"en": "Layers", "kr": "레이어", "jp": "レイヤー", "cn": "图层"},
            "tab_naming": {"en": "Naming", "kr": "네이밍", "jp": "命名", "cn": "命名"},
            "tab_picker": {"en": "Picker", "kr": "피커", "jp": "ピッカー", "cn": "选择器"},
            "tab_pose": {"en": "Pose", "kr": "포즈", "jp": "ポーズ", "cn": "姿态"},
            "tab_bone": {"en": "Bone", "kr": "본 (Bone)", "jp": "ボーン", "cn": "骨骼"},
            "tab_info": {"en": "Info", "kr": "정보", "jp": "情報", "cn": "信息"},

            # ========================================================
            # [1] Edit Mesh Tab
            # ========================================================
            "em_refresh_btn": {"en": "Refresh List", "kr": "리스트 갱신", "jp": "リスト更新", "cn": "刷新列表"},
            "em_scene_meshes": {"en": "Scene Meshes:", "kr": "씬 메시 목록:", "jp": "シーンメッシュ:", "cn": "场景网格:"},
            "em_btn_finalize": {"en": "Finalize Mesh", "kr": "메시 확정", "jp": "メッシュ確定", "cn": "完成网格"},
            "em_grp_inspector": {"en": "Mesh Inspector", "kr": "메시 검사기", "jp": "メッシュ検査", "cn": "网格检查器"},
            "em_grp_details": {"en": "Details & Fix", "kr": "상세 및 수정", "jp": "詳細と修正", "cn": "详情与修复"},
            "em_grp_finalize": {"en": "Finalize Options", "kr": "확정 옵션", "jp": "確定オプション", "cn": "完成选项"},
            "em_col_check": {"en": "Check Item", "kr": "검사 항목", "jp": "検査項目", "cn": "检查项目"},
            "em_col_status": {"en": "Status", "kr": "상태", "jp": "状態", "cn": "状态"},
            "em_col_details": {"en": "Action", "kr": "수정", "jp": "修正", "cn": "操作"},
            "em_opt_lock": {"en": "Lock Transform", "kr": "트랜스폼 잠금", "jp": "トランスフォーム固定", "cn": "锁定变换"},
            "em_opt_inherit": {"en": "Inheritance", "kr": "상속 재설정", "jp": "継承リセット", "cn": "重置继承"},
            "em_opt_skin": {"en": "Add Skin", "kr": "스킨 추가", "jp": "スキン追加", "cn": "添加蒙皮"},
            "em_opt_dq": {"en": "Dual Quat", "kr": "듀얼 쿼터니언", "jp": "DQ有効化", "cn": "双四元数"},
            "em_opt_limit": {"en": "Bone Limit", "kr": "본 제한", "jp": "ボーン制限", "cn": "骨骼限制"},
            "tip_em_lock": {"en": "Lock all transforms.", "kr": "모든 트랜스폼 잠금.", "jp": "全トランスフォーム固定。",
                            "cn": "锁定所有变换。"},
            "tip_em_inherit": {"en": "Reset Inheritance.", "kr": "상속 초기화.", "jp": "継承リセット。", "cn": "重置继承。"},
            "tip_em_skin": {"en": "Add Skin modifier.", "kr": "스킨 추가.", "jp": "スキン追加。", "cn": "添加蒙皮。"},
            "tip_em_dq": {"en": "Enable Dual Quaternion.", "kr": "듀얼 쿼터니언 켜기.", "jp": "DQ有効化。", "cn": "启用DQ。"},
            "tip_em_limit": {"en": "Set Bone Limit.", "kr": "본 개수 제한.", "jp": "ボーン数制限。", "cn": "设置骨骼限制。"},
            "chk_scale_lbl": {"en": "Uniform Scale", "kr": "스케일 (1,1,1)", "jp": "スケール初期化", "cn": "统一缩放"},
            "chk_scale_inf": {"en": "Scale is not (1,1,1).", "kr": "스케일 오류.", "jp": "スケールエラー。",
                              "cn": "缩放错误。"},
            "chk_scale_fix": {"en": "Reset XForm", "kr": "XForm 리셋", "jp": "XFormリセット", "cn": "重置XForm"},
            "chk_skin_lbl": {"en": "Clean Stack", "kr": "스택 (No Skin)", "jp": "スタック整理", "cn": "清理堆栈"},
            "chk_skin_inf": {"en": "Skin modifier exists.", "kr": "스킨 존재.", "jp": "スキンあり。", "cn": "存在蒙皮。"},
            "chk_skin_fix": {"en": "Delete Skin", "kr": "스킨 삭제", "jp": "スキン削除", "cn": "删除蒙皮"},
            "chk_pivot_lbl": {"en": "Pivot at Origin", "kr": "피벗 원점", "jp": "ピボット原点", "cn": "轴心原点"},
            "chk_pivot_inf": {"en": "Pivot not at (0,0,0).", "kr": "피벗 위치 오류.", "jp": "ピボット位置エラー。",
                              "cn": "轴心错误。"},
            "chk_pivot_fix": {"en": "Move to Origin", "kr": "원점이동", "jp": "原点移動", "cn": "移至原点"},
            "em_welcome_msg": {"en": "Select a mesh.", "kr": "메시를 선택하세요.", "jp": "メッシュ選択。", "cn": "选择网格。"},
            "msg_no_mesh": {"en": "No meshes found.", "kr": "메시 없음.", "jp": "メッシュなし。", "cn": "未找到网格。"},
            "btn_show_details": {"en": "Details", "kr": "상세", "jp": "詳細", "cn": "详情"},
            "lbl_value": {"en": "Value:", "kr": "값:", "jp": "値:", "cn": "值:"},
            "lbl_no_issues": {"en": "No issues found.", "kr": "문제 없음.", "jp": "問題なし。", "cn": "无问题。"},

            # ========================================================
            # [2] Rigging Tab Keys
            # ========================================================
            "rig_tab_biped": {"en": "Biped", "kr": "바이패드", "jp": "バイペッド", "cn": "Biped"},
            "rig_tab_bone": {"en": "Bone", "kr": "본", "jp": "ボーン", "cn": "骨骼"},
            "rig_tab_layers": {"en": "Layers", "kr": "레이어", "jp": "レイヤー", "cn": "图层"},
            "rig_tab_naming": {"en": "Naming", "kr": "네이밍", "jp": "命名", "cn": "命名"},
            "rig_tab_picker": {"en": "Picker", "kr": "피커", "jp": "ピッカー", "cn": "选择器"},
            "rig_tab_pose": {"en": "Pose", "kr": "포즈", "jp": "ポーズ", "cn": "姿态"},

            "rig_grp_struct": {"en": "1. Structure", "kr": "1. 구조 설정", "jp": "1. 構造設定", "cn": "1. 结构设置"},
            "rig_lbl_spine": {"en": "Spine:", "kr": "척추:", "jp": "背骨:", "cn": "脊椎:"},
            "rig_lbl_neck": {"en": "Neck:", "kr": "목:", "jp": "首:", "cn": "颈部:"},
            "rig_chk_tripelvis": {"en": "Tri Pelvis", "kr": "삼각 골반", "jp": "三角骨盤", "cn": "三角骨盆"},
            "rig_chk_trineck": {"en": "Tri Neck", "kr": "삼각 목", "jp": "三角首", "cn": "三角颈"},
            "rig_lbl_fingers": {"en": "Fingers:", "kr": "손가락:", "jp": "指:", "cn": "手指:"},
            "rig_lbl_flinks": {"en": "F. Links:", "kr": "손가락 마디:", "jp": "指関節:", "cn": "指节:"},
            "rig_lbl_toes": {"en": "Toes:", "kr": "발가락:", "jp": "足指:", "cn": "脚趾:"},
            "rig_lbl_tlinks": {"en": "T. Links:", "kr": "발가락 마디:", "jp": "足指関節:", "cn": "趾节:"},
            "rig_lbl_leglinks": {"en": "Leg Links:", "kr": "다리 관절:", "jp": "脚関節:", "cn": "腿部关节:"},
            "rig_lbl_tail": {"en": "Tail:", "kr": "꼬리:", "jp": "尻尾:", "cn": "尾巴:"},
            "rig_lbl_pony1": {"en": "Pony 1:", "kr": "포니테일 1:", "jp": "ポニー 1:", "cn": "马尾 1:"},
            "rig_lbl_pony2": {"en": "Pony 2:", "kr": "포니테일 2:", "jp": "ポニー 2:", "cn": "马尾 2:"},
            "rig_grp_work": {"en": "2. Workflow", "kr": "2. 워크플로우", "jp": "2. ワークフロー", "cn": "2. 工作流程"},
            "rig_grp_work_hint": {"en": " * Sequence", "kr": " * 순서대로 실행", "jp": " * 順次実行", "cn": " * 按顺序执行"},
            "rig_btn_create_guides": {"en": "1. Create Guides", "kr": "1. 가이드 생성", "jp": "1. ガイド作成",
                                      "cn": "1. 创建向导"},
            "rig_btn_align_short": {"en": "2. Joint LookAt", "kr": "2. 관절 정렬", "jp": "2. 整列", "cn": "2. 关节朝向"},
            "rig_btn_gen_biped": {"en": "3. Generate Biped", "kr": "3. 바이패드 생성", "jp": "3. 生成", "cn": "3. 生成Biped"},
            "rig_lbl_guide_expl": {"en": "Guide Explorer", "kr": "가이드 탐색기", "jp": "ガイド一覧", "cn": "向导列表"},
            "rig_ph_search": {"en": "Search...", "kr": "검색...", "jp": "検索...", "cn": "搜索..."},
            "rig_btn_snap": {"en": "Snap to Verts", "kr": "버텍스 스냅", "jp": "頂点スナップ", "cn": "吸附顶点"},
            "rig_btn_mirror": {"en": "Mirror Guides", "kr": "가이드 대칭", "jp": "ガイドミラー", "cn": "向导镜像"},

            "bone_grp_create": {"en": "Creation", "kr": "본 생성", "jp": "作成", "cn": "创建"},
            "bone_lbl_base": {"en": "Name:", "kr": "이름:", "jp": "名前:", "cn": "名称:"},
            "bone_lbl_cnt": {"en": "Count:", "kr": "개수:", "jp": "数:", "cn": "数量:"},
            "bone_btn_create": {"en": "Create Bone Chain", "kr": "본 체인 생성", "jp": "ボーンチェーン作成",
                                "cn": "创建骨链"},
            "bone_grp_opt": {"en": "Options", "kr": "옵션", "jp": "オプション", "cn": "选项"},
            "bone_lbl_wh": {"en": "W/H:", "kr": "너비/높이:", "jp": "幅/高さ:", "cn": "宽/高:"},
            "bone_lbl_taper": {"en": "Taper:", "kr": "테이퍼:", "jp": "テーパー:", "cn": "锥度:"},
            "bone_btn_fin_side": {"en": "Side Fin", "kr": "사이드 핀", "jp": "サイドフィン", "cn": "侧鳍"},
            "bone_btn_fin_front": {"en": "Front Fin", "kr": "프론트 핀", "jp": "フロントフィン", "cn": "前鳍"},
            "bone_btn_fin_back": {"en": "Back Fin", "kr": "백 핀", "jp": "バックフィン", "cn": "后鳍"},
            "bone_grp_mirror": {"en": "Mirror Tool", "kr": "미러 도구", "jp": "ミラーツール", "cn": "镜像工具"},
            "bone_lbl_axis": {"en": "Axis:", "kr": "축:", "jp": "軸:", "cn": "轴:"},
            "bone_lbl_flip": {"en": "Flip:", "kr": "뒤집기:", "jp": "反転:", "cn": "翻转:"},
            "bone_lbl_offset": {"en": "Offset:", "kr": "오프셋:", "jp": "オフセット:", "cn": "偏移:"},
            "bone_lbl_gizmo_size": {"en": "Size:", "kr": "크기:", "jp": "サイズ:", "cn": "大小:"},
            "bone_btn_helper": {"en": "Create Gizmo", "kr": "기즈모 생성", "jp": "ギズモ作成", "cn": "创建辅助"},
            "bone_btn_mirror": {"en": "Mirror Bones", "kr": "본 미러 실행", "jp": "ボーンミラー", "cn": "镜像骨骼"},
            "bone_grp_color": {"en": "Colorize", "kr": "색상 지정", "jp": "色指定", "cn": "着色"},
            "bone_chk_grad": {"en": "Gradient", "kr": "그라데이션", "jp": "グラデーション", "cn": "渐变"},
            "bone_btn_color_apply": {"en": "Apply", "kr": "적용", "jp": "適用", "cn": "应用"},
            "bone_grp_stretch": {"en": "Stretch Tool", "kr": "스트레치 도구", "jp": "ストレッチツール", "cn": "伸缩工具"},
            "bone_lbl_stretch_hint": {"en": "Select bones and click Apply.", "kr": "본을 선택하고 적용하세요.",
                                      "jp": "ボーンを選択して適用。", "cn": "选择骨骼并应用。"},
            "bone_btn_apply_stretch": {"en": "Apply Stretch", "kr": "스트레치 적용", "jp": "ストレッチ適用",
                                       "cn": "应用伸缩"},
            "bone_grp_ctrl": {"en": "Create Controllers", "kr": "컨트롤러 생성", "jp": "コントローラ作成",
                              "cn": "创建控制器"},

            "rig_grp_twist": {"en": "Twist Bone Tool", "kr": "트위스트 본 도구", "jp": "ツイストツール", "cn": "扭曲骨骼工具"},
            "rig_lbl_twist_count": {"en": "Count:", "kr": "개수:", "jp": "数:", "cn": "数量:"},
            "rig_lbl_twist_mode": {"en": "Mode:", "kr": "모드:", "jp": "モード:", "cn": "模式:"},
            "rig_mode_parent": {"en": "Parent", "kr": "부모 기준", "jp": "親基準", "cn": "父级"},
            "rig_mode_child": {"en": "Child", "kr": "자식 기준", "jp": "子基準", "cn": "子级"},
            "rig_btn_create_twist_run": {"en": "Create Twist Bones", "kr": "트위스트 본 생성", "jp": "作成", "cn": "创建"},

            "rig_grp_inspector": {"en": "Controller Inspector", "kr": "컨트롤러 인스펙터", "jp": "コントローラ検査",
                                  "cn": "控制器检查"},
            "insp_grp_info": {"en": "Node Info", "kr": "노드 정보", "jp": "ノード情報", "cn": "节点信息"},
            "insp_btn_load": {"en": "Load Selected", "kr": "선택 불러오기", "jp": "選択読込", "cn": "加载所选"},
            "insp_lbl_track": {"en": "Track Name", "kr": "트랙 이름", "jp": "トラック名", "cn": "轨道名称"},
            "insp_lbl_type": {"en": "Type", "kr": "유형", "jp": "タイプ", "cn": "类型"},
            "insp_btn_assign": {"en": "Assign", "kr": "할당", "jp": "割当", "cn": "分配"},
            "insp_lbl_script": {"en": "Script Code:", "kr": "스크립트 코드:", "jp": "スクリプト:", "cn": "脚本代码:"},
            "insp_btn_apply_script": {"en": "Apply Code", "kr": "코드 적용", "jp": "適用", "cn": "应用代码"},
            "insp_lbl_expr": {"en": "Expression Code:", "kr": "표현식 코드:", "jp": "式:", "cn": "表达式代码:"},
            "insp_btn_apply_expr": {"en": "Apply Expression", "kr": "표현식 적용", "jp": "適用", "cn": "应用表达式"},
            "insp_lbl_targets": {"en": "Constraint Targets:", "kr": "컨스트레인 타겟:", "jp": "ターゲット:",
                                 "cn": "约束目标:"},
            "insp_col_target": {"en": "Target Node", "kr": "타겟 노드", "jp": "ターゲット", "cn": "目标节点"},
            "insp_col_weight": {"en": "Weight", "kr": "가중치", "jp": "ウェイト", "cn": "权重"},
            "insp_btn_add_tgt": {"en": "Add Selected", "kr": "선택 추가", "jp": "選択追加", "cn": "添加所选"},
            "insp_btn_rem_tgt": {"en": "Remove", "kr": "제거", "jp": "除去", "cn": "移除"},
            "insp_btn_set_w": {"en": "Set Weight", "kr": "가중치 설정", "jp": "ウェイト設定", "cn": "设置权重"},

            "rig_grp_transform": {"en": "Pose Transform", "kr": "포즈 트랜스폼", "jp": "ポーズ変形", "cn": "姿态变换"},
            "rig_btn_copy_pose": {"en": "Copy", "kr": "복사", "jp": "コピー", "cn": "复制"},
            "rig_btn_paste_pose": {"en": "Paste", "kr": "붙여넣기", "jp": "貼付", "cn": "粘贴"},
            "rig_chk_pos": {"en": "Pos", "kr": "위치", "jp": "位置", "cn": "位置"},
            "rig_chk_rot": {"en": "Rot", "kr": "회전", "jp": "回転", "cn": "旋转"},
            "rig_btn_mirror_paste": {"en": "Mirror Paste", "kr": "대칭 붙여넣기", "jp": "ミラー貼付", "cn": "镜像粘贴"},

            # ========================================================
            # [3] Skinning Tab
            # ========================================================
            "skin_grp_mesh_hide": {"en": "Hide Mesh", "kr": "메시 숨기기", "jp": "メッシュ非表示", "cn": "隐藏网格"},
            "skin_hide_info_lbl": {"en": "Select Face/Element.", "kr": "면/엘리먼트 선택.", "jp": "面/要素選択。",
                                   "cn": "选择面/元素。"},
            "skin_lbl_hide_unselected": {"en": "Invert", "kr": "반전", "jp": "反転", "cn": "反转"},
            "skin_btn_face": {"en": "Face", "kr": "면", "jp": "面", "cn": "面"},
            "skin_btn_element": {"en": "Element", "kr": "엘리먼트", "jp": "要素", "cn": "元素"},
            "skin_btn_unhide": {"en": "Unhide All", "kr": "모두 보이기", "jp": "全表示", "cn": "全部显示"},
            "tip_hide_invert": {"en": "Hide unselected parts.", "kr": "선택하지 않은 부분 숨기기.", "jp": "選択外を非表示。",
                                "cn": "隐藏未选。"},

            "skin_grp_layers": {"en": "Layer Skinning", "kr": "레이어 스키닝", "jp": "レイヤースキニング", "cn": "图层蒙皮"},
            "skin_btn_import": {"en": "Import", "kr": "가져오기", "jp": "インポート", "cn": "导入"},
            "skin_btn_collapse": {"en": "Collapse", "kr": "합치기", "jp": "統合", "cn": "合并"},

            "skin_btn_manual_edit": {"en": "Edit", "kr": "편집", "jp": "編集", "cn": "编辑"},
            "skin_btn_paint": {"en": "Paint", "kr": "페인트", "jp": "ペイント", "cn": "绘制"},
            "skin_btn_paint_options": {"en": "Opt", "kr": "옵션", "jp": "OP", "cn": "选项"},
            "skin_lbl_blend_mode": {"en": "Blend:", "kr": "혼합:", "jp": "ブレンド:", "cn": "混合:"},
            "skin_btn_inject": {"en": "Inject", "kr": "적용", "jp": "適用", "cn": "注入"},
            "skin_btn_paint_options_tip": {"en": "Paint Options", "kr": "페인트 옵션", "jp": "オプション", "cn": "选项"},

            "tooltip_import": {"en": "Import base weights.", "kr": "베이스 웨이트 가져오기.", "jp": "ベース読込。",
                               "cn": "导入基础。"},
            "tooltip_collapse": {"en": "Collapse all layers.", "kr": "모든 레이어 합치기.", "jp": "全統合。", "cn": "全部合并。"},
            "tooltip_add_layer": {"en": "Add new layer.", "kr": "레이어 추가.", "jp": "追加。", "cn": "添加。"},
            "tooltip_rem_layer": {"en": "Remove layer.", "kr": "레이어 삭제.", "jp": "削除。", "cn": "删除。"},
            "tooltip_move_up": {"en": "Move Up", "kr": "위로", "jp": "上へ", "cn": "上移"},
            "tooltip_move_down": {"en": "Move Down", "kr": "아래로", "jp": "下へ", "cn": "下移"},
            "tooltip_manual_edit": {"en": "Edit Mode.", "kr": "편집 모드.", "jp": "編集モード。", "cn": "编辑模式。"},
            "tooltip_paint": {"en": "Paint Mode.", "kr": "페인트 모드.", "jp": "ペイント。", "cn": "绘制。"},
            "tooltip_inject": {"en": "Inject to Skin.", "kr": "스킨에 적용.", "jp": "スキン適用。", "cn": "应用。"},

            "btn_rem_useless": {"en": "Rem Unused", "kr": "미사용 제거", "jp": "未使用削除", "cn": "移除未用"},
            "tip_rem_useless": {"en": "Remove 0 weight bones.", "kr": "웨이트 0 본 제거.", "jp": "ウェイト0削除。",
                                "cn": "移除0权重。"},
            "btn_bnlist_vert": {"en": "Find Bone", "kr": "본 찾기", "jp": "ボーン検索", "cn": "查找骨骼"},
            "tip_bnlist_vert": {"en": "Find bones by vert.", "kr": "버텍스로 본 찾기.", "jp": "頂点で検索。",
                                "cn": "按顶点查找。"},
            "btn_clear_filter": {"en": "Clear", "kr": "초기화", "jp": "クリア", "cn": "清除"},
            "tip_clear_filter": {"en": "Clear filter.", "kr": "필터 해제.", "jp": "フィルタ解除。", "cn": "清除过滤。"},
            "btn_transfer": {"en": "Transfer", "kr": "전송", "jp": "転送", "cn": "传递"},
            "tip_transfer": {"en": "Transfer weights.", "kr": "웨이트 전송.", "jp": "ウェイト転送。", "cn": "传递权重。"},
            "btn_rem_zero": {"en": "Prune", "kr": "정리", "jp": "整理", "cn": "清理"},
            "tip_rem_zero": {"en": "Prune small weights.", "kr": "미세 웨이트 제거.", "jp": "微細除去。", "cn": "清理微小。"},
            "btn_save_bnlist": {"en": "Save List", "kr": "리스트 저장", "jp": "リスト保存", "cn": "保存列表"},
            "tip_save_bnlist": {"en": "Save bone list.", "kr": "본 리스트 저장.", "jp": "ボーンリスト保存。",
                                "cn": "保存骨骼列表。"},
            "btn_load_bnlist": {"en": "Load List", "kr": "리스트 로드", "jp": "リスト読込", "cn": "加载列表"},
            "tip_load_bnlist": {"en": "Load bone list.", "kr": "본 리스트 불러오기.", "jp": "ボーンリスト読込。",
                                "cn": "加载骨骼列表。"},
            "btn_save_skin": {"en": "Save .env", "kr": ".env 저장", "jp": ".env保存", "cn": "保存.env"},
            "tip_save_skin": {"en": "Save .env file.", "kr": ".env 파일 저장.", "jp": ".env保存。", "cn": "保存.env。"},
            "btn_load_skin": {"en": "Load .env", "kr": ".env 로드", "jp": ".env読込", "cn": "加载.env"},
            "tip_load_skin": {"en": "Load .env file.", "kr": ".env 파일 로드.", "jp": ".env読込。", "cn": "加载.env。"},
            "btn_export_skindata": {"en": "Export Data", "kr": "데이터 내보내기", "jp": "データ出力", "cn": "导出数据"},
            "tip_export_skindata": {"en": "Export ohCHA data.", "kr": "ohCHA 데이터 내보내기.", "jp": "独自データ出力。",
                                    "cn": "导出数据。"},
            "btn_import_skindata": {"en": "Import Data", "kr": "데이터 가져오기", "jp": "データ入力", "cn": "导入数据"},
            "tip_import_skindata": {"en": "Import ohCHA data.", "kr": "ohCHA 데이터 가져오기.", "jp": "独自数据输入。",
                                    "cn": "导入数据。"},

            "btn_grow": {"en": "Grow", "kr": "확장", "jp": "拡大", "cn": "扩展"},
            "tip_grow": {"en": "Grow Selection", "kr": "선택 확장", "jp": "選択拡大", "cn": "扩展选择"},
            "btn_shrink": {"en": "Shrink", "kr": "축소", "jp": "縮小", "cn": "收缩"},
            "tip_shrink": {"en": "Shrink Selection", "kr": "선택 축소", "jp": "選択縮小", "cn": "收缩选择"},
            "btn_loop": {"en": "Loop", "kr": "루프", "jp": "ループ", "cn": "循环"},
            "tip_loop": {"en": "Select Loop", "kr": "루프 선택", "jp": "ループ選択", "cn": "循环选择"},
            "btn_ring": {"en": "Ring", "kr": "링", "jp": "リング", "cn": "环形"},
            "tip_ring": {"en": "Select Ring", "kr": "링 선택", "jp": "リング選択", "cn": "环形选择"},
            "btn_copy": {"en": "Copy", "kr": "복사", "jp": "コピー", "cn": "复制"},
            "tip_copy": {"en": "Copy Weight", "kr": "웨이트 복사", "jp": "ウェイトコピー", "cn": "复制权重"},
            "btn_paste": {"en": "Paste", "kr": "붙여넣기", "jp": "貼付", "cn": "粘贴"},
            "tip_paste": {"en": "Paste Weight", "kr": "웨이트 붙여넣기", "jp": "ウェイト貼付", "cn": "粘贴权重"},
            "btn_smooth": {"en": "Smooth", "kr": "스무스", "jp": "スムース", "cn": "平滑"},
            "tip_smooth": {"en": "Smooth Weights", "kr": "웨이트 스무스", "jp": "ウェイトスムース", "cn": "平滑权重"},
            "btn_heal": {"en": "Heal", "kr": "힐", "jp": "ヒール", "cn": "修复"},
            "tip_heal": {"en": "Heal Weights", "kr": "웨이트 힐", "jp": "ウェイトヒール", "cn": "修复权重"},
            "tip_val_add": {"en": "Add", "kr": "더하기", "jp": "加算", "cn": "添加"},
            "tip_val_sub": {"en": "Subtract", "kr": "빼기", "jp": "減算", "cn": "减去"},
            "tip_val_spinner": {"en": "Step", "kr": "단계", "jp": "ステップ", "cn": "步长"},
            "tip_val_preset": {"en": "Set", "kr": "설정", "jp": "設定", "cn": "设定"},

            # [Bone List Explorer] ⭐️ Added Missing Keys
            "view_label": {"en": "View:", "kr": "보기:", "jp": "表示:", "cn": "视图:"},
            "search_ph": {"en": "Search bones...", "kr": "본 검색...", "jp": "ボーン検索...", "cn": "搜索骨骼..."},

            # [Layer Tool]
            "layer_btn_save": {"en": "Save Preset", "kr": "프리셋 저장", "jp": "プリセット保存", "cn": "保存预设"},
            "layer_btn_load": {"en": "Load Preset", "kr": "프리셋 불러오기", "jp": "プリセット読込", "cn": "加载预设"},
            "layer_lbl_hierarchy": {"en": "Layer Hierarchy", "kr": "레이어 계층구조", "jp": "レイヤー階層", "cn": "图层层级"},
            "layer_ph_new": {"en": "New Layer Name...", "kr": "새 레이어 이름...", "jp": "新規レイヤー名...",
                             "cn": "新图层名..."},
            "layer_ph_search": {"en": "Search...", "kr": "검색...", "jp": "検索...", "cn": "搜索..."},
            "layer_btn_sel_obj": {"en": "Sel Obj", "kr": "객체선택", "jp": "Obj選択", "cn": "选对象"},
            "layer_btn_rename": {"en": "Rename", "kr": "이름변경", "jp": "名前変更", "cn": "重命名"},
            "layer_btn_del": {"en": "Del", "kr": "삭제", "jp": "削除", "cn": "删除"},
            "layer_tip_assign": {"en": "Assign Objects", "kr": "객체 할당", "jp": "オブジェクト割当", "cn": "分配对象"},
            "layer_lbl_scene": {"en": "Scene Objects", "kr": "씬 오브젝트", "jp": "シーンオブジェクト", "cn": "场景对象"},
            "layer_tip_refresh": {"en": "Refresh List", "kr": "목록 갱신", "jp": "リスト更新", "cn": "刷新"},
            "layer_btn_add": {"en": "Add", "kr": "추가", "jp": "追加", "cn": "添加"},
            "layer_btn_refresh": {"en": "Refresh", "kr": "새로고침", "jp": "更新", "cn": "刷新"},
            "layer_col_name": {"en": "Name", "kr": "이름", "jp": "名前", "cn": "名称"},
            "layer_col_layer": {"en": "Layer", "kr": "레이어", "jp": "レイヤー", "cn": "图层"},
            "layer_col_type": {"en": "Type", "kr": "타입", "jp": "タイプ", "cn": "类型"},
            "layer_msg_del_title": {"en": "Delete Layer", "kr": "레이어 삭제", "jp": "レイヤー削除", "cn": "删除图层"},
            "layer_msg_del_confirm": {"en": "Delete '{}'?", "kr": "'{}' 삭제하시겠습니까?", "jp": "'{}' 削除？",
                                      "cn": "删除 '{}'?"},
            "layer_msg_ren_title": {"en": "Rename Layer", "kr": "레이어 이름 변경", "jp": "レイヤー名変更", "cn": "重命名"},
            "layer_msg_ren_label": {"en": "New Name:", "kr": "새 이름:", "jp": "新名前:", "cn": "新名称:"},
            "layer_msg_success": {"en": "Success", "kr": "성공", "jp": "成功", "cn": "成功"},
            "layer_msg_err": {"en": "Error", "kr": "오류", "jp": "エラー", "cn": "错误"},
            "layer_msg_saved": {"en": "Preset Saved.", "kr": "프리셋 저장됨.", "jp": "プリセット保存。", "cn": "预设已保存。"},
            "layer_msg_loaded": {"en": "Preset Loaded.", "kr": "프리셋 로드됨.", "jp": "プリセット読込。",
                                 "cn": "预设已加载。"},
            "layer_msg_fail": {"en": "Failed.", "kr": "실패.", "jp": "失敗。", "cn": "失败。"},

            # [Naming Tool]
            "name_grp_sel": {"en": "Selection", "kr": "선택", "jp": "選択", "cn": "选择"},
            "name_btn_load": {"en": "Load Selected", "kr": "선택 불러오기", "jp": "選択読込", "cn": "加载所选"},
            "name_lbl_count": {"en": "Count: {}", "kr": "개수: {}", "jp": "数: {}", "cn": "数量: {}"},
            "name_grp_base": {"en": "Base Name", "kr": "기본 이름", "jp": "基本名", "cn": "基本名称"},
            "name_chk_base": {"en": "Use Base Name", "kr": "기본 이름 사용", "jp": "基本名使用", "cn": "使用基本名"},
            "name_grp_mod": {"en": "Naming Rules", "kr": "이름 규칙", "jp": "命名規則", "cn": "命名规则"},
            "name_lbl_pre": {"en": "Prefix:", "kr": "접두사:", "jp": "接頭辞:", "cn": "前缀:"},
            "name_lbl_suf": {"en": "Suffix:", "kr": "접미사:", "jp": "接尾辞:", "cn": "后缀:"},
            "name_grp_rem": {"en": "Remove Digits", "kr": "문자 제거", "jp": "文字削除", "cn": "移除字符"},
            "name_lbl_rem_f": {"en": "Rem First:", "kr": "앞 제거:", "jp": "先頭削除:", "cn": "前除:"},
            "name_lbl_rem_l": {"en": "Rem Last:", "kr": "뒤 제거:", "jp": "末尾削除:", "cn": "后除:"},
            "name_grp_num": {"en": "Numbering", "kr": "번호 매기기", "jp": "ナンバリング", "cn": "编号"},
            "name_chk_num": {"en": "Enable", "kr": "사용", "jp": "使用", "cn": "启用"},
            "name_lbl_start": {"en": "Start:", "kr": "시작:", "jp": "開始:", "cn": "开始:"},
            "name_lbl_step": {"en": "Step:", "kr": "간격:", "jp": "増分:", "cn": "步长:"},
            "name_lbl_pad": {"en": "Pad:", "kr": "자릿수:", "jp": "桁数:", "cn": "位数:"},
            "name_col_curr": {"en": "Current Name", "kr": "현재 이름", "jp": "現在の名前", "cn": "当前名称"},
            "name_col_new": {"en": "New Name", "kr": "새 이름", "jp": "新しい名前", "cn": "新名称"},
            "name_btn_apply": {"en": "Rename Objects", "kr": "이름 변경 적용", "jp": "名前変更適用", "cn": "应用重命名"},
            "name_msg_success": {"en": "Renamed {} objects.", "kr": "{}개 객체 이름 변경 완료.", "jp": "{} 個の名前を変更。",
                                 "cn": "已重命名 {} 个对象。"},
            "name_msg_no_sel": {"en": "No selection.", "kr": "선택된 객체 없음.", "jp": "選択なし。", "cn": "无选择。"},

            # [Common]
            "btn_grp_add": {"en": "+ Grp", "kr": "+ 그룹", "jp": "+ G", "cn": "+ 组"},
            "btn_grp_rem": {"en": "- Grp", "kr": "- 그룹", "jp": "- G", "cn": "- 组"},
            "btn_grp_ren": {"en": "Ren", "kr": "이름", "jp": "名", "cn": "名"},
            "btn_assign": {"en": "Assign", "kr": "할당", "jp": "割当", "cn": "分配"},
            "ctx_remove_infl": {"en": "Remove Influence", "kr": "영향 제거", "jp": "影響削除", "cn": "移除影响"},
            "layer_btn_mask_add": {"en": "+ Mask", "kr": "+ 마스크", "jp": "+ マスク", "cn": "+ 蒙版"},
            "layer_btn_mask_rem": {"en": "- Mask", "kr": "- 마스크", "jp": "- マスク", "cn": "- 蒙版"},
            "mask_btn_add": {"en": "+ Add", "kr": "+ 추가", "jp": "+ 追加", "cn": "+ 添加"},
            "mask_btn_sub": {"en": "- Sub", "kr": "- 제거", "jp": "- 除去", "cn": "- 移除"},
            "mask_btn_sel": {"en": "Select", "kr": "선택", "jp": "選択", "cn": "选择"},
            "tip_toggle_mask": {"en": "Toggle Mask", "kr": "마스크 토글", "jp": "マスク切替", "cn": "切换蒙版"},
            "tip_toggle_layer": {"en": "Toggle Layer", "kr": "레이어 토글", "jp": "レイヤー切替", "cn": "切换图层"},
            "info_version": {"en": "Version", "kr": "버전", "jp": "バージョン", "cn": "版本"},
            "info_how_to_use_title": {"en": "How to Use", "kr": "사용법", "jp": "使用方法", "cn": "使用方法"},
            "info_how_to_use_content": {"en": "Online Manual (Notion)", "kr": "온라인 매뉴얼 (Notion)",
                                        "jp": "オンラインマニュアル", "cn": "在线手册"},
            "info_copyright": {"en": "© 2025 CHA SEUNGHYEON.", "kr": "© 2025 CHA SEUNGHYEON.",
                               "jp": "© 2025 CHA SEUNGHYEON.", "cn": "© 2025 CHA SEUNGHYEON."},
            "info_contact": {"en": "Contact", "kr": "문의", "jp": "連絡先", "cn": "联系"},
            "title_error": {"en": "Error", "kr": "오류", "jp": "エラー", "cn": "错误"},
            "title_warning": {"en": "Warning", "kr": "경고", "jp": "警告", "cn": "警告"},
            "title_info": {"en": "Info", "kr": "알림", "jp": "情報", "cn": "信息"},
            "title_confirm": {"en": "Confirm", "kr": "확인", "jp": "確認", "cn": "确认"},
            "title_notification": {"en": "Notify", "kr": "알림", "jp": "通知", "cn": "通知"},
            "title_save_complete": {"en": "Saved", "kr": "저장됨", "jp": "保存 완료", "cn": "已保存"},
            "title_complete": {"en": "Done", "kr": "완료", "jp": "完了", "cn": "完成"},
            "title_import_base": {"en": "Import Base", "kr": "베이스 가져오기", "jp": "ベース読込", "cn": "导入基础"},
            "msg_import_base": {"en": "Import from '{}'?", "kr": "'{}'에서 가져오시겠습니까?", "jp": "'{}'から読込？",
                                "cn": "从 '{}' 导入？"},
            "msg_save_complete": {"en": "Saved '{}'.", "kr": "'{}' 저장 완료.", "jp": "'{}' 保存。", "cn": "'{}' 已保存。"},
            "msg_done": {"en": "Operation Done.", "kr": "작업 완료.", "jp": "作業完了。", "cn": "操作完成。"},
            "msg_error_paint": {"en": "Paint Failed.", "kr": "페인트 실패.", "jp": "ペイント失敗。", "cn": "绘制失败。"},
            "msg_error_manual_edit": {"en": "Edit Failed.", "kr": "편집 실패.", "jp": "編集失敗。", "cn": "编辑失败。"},
            "title_layer_selection": {"en": "Select Layer", "kr": "레이어 선택", "jp": "レイヤー選択", "cn": "选择图层"},
            "msg_layer_selection_paint": {"en": "Select a layer.", "kr": "레이어를 선택하세요.", "jp": "レイヤーを選択。",
                                          "cn": "选择图层。"},
            "msg_layer_selection_manual_edit": {"en": "Select a layer.", "kr": "레이어를 선택하세요.", "jp": "レイヤーを選択。",
                                                "cn": "选择图层。"},
            "title_enter_manual_edit": {"en": "Edit Mode", "kr": "편집 모드", "jp": "編集モード", "cn": "编辑模式"},
            "msg_enter_manual_edit": {"en": "Enter Edit Mode?", "kr": "편집 모드 진입?", "jp": "編集モード？",
                                      "cn": "进入编辑模式？"},
            "msg_manual_edit_saved": {"en": "Edit Saved.", "kr": "편집 저장됨.", "jp": "編集保存。", "cn": "编辑已保存。"},
            "msg_paint_saved": {"en": "Paint Saved.", "kr": "페인트 저장됨.", "jp": "ペイント保存。", "cn": "绘制已保存。"},
            "title_collapse_layers": {"en": "Collapse", "kr": "합치기", "jp": "統合", "cn": "合并"},
            "msg_collapse_layers": {"en": "Collapse all?", "kr": "모두 합치시겠습니까?", "jp": "全て統合？", "cn": "全部合并？"},
            "msg_collapse_complete": {"en": "Collapsed.", "kr": "합쳐졌습니다.", "jp": "統合完了。", "cn": "已合并。"},
            "title_bone_selection": {"en": "Select Bone", "kr": "본 선택", "jp": "ボーン選択", "cn": "选择骨骼"},
            "msg_bone_selection_mask": {"en": "Select bones.", "kr": "본을 선택하세요.", "jp": "ボーンを選択。",
                                        "cn": "选择骨骼。"},
            "msg_bone_selection_check": {"en": "Select bones.", "kr": "본을 선택하세요.", "jp": "ボーンを選択。",
                                         "cn": "选择骨骼。"},
            "msg_mask_select_success": {"en": "Selected {} verts.", "kr": "{}개 버텍스 선택.", "jp": "{} 頂点選択。",
                                        "cn": "选中 {} 个顶点。"},
            "msg_no_mask_data": {"en": "No data.", "kr": "데이터 없음.", "jp": "データなし。", "cn": "无数据。"},
            "pop_add_group_title": {"en": "Add Group", "kr": "그룹 추가", "jp": "G追加", "cn": "添加组"},
            "pop_add_group_label": {"en": "Name:", "kr": "이름:", "jp": "名前:", "cn": "名称:"},
            "pop_group_exists": {"en": "Exists.", "kr": "이미 존재합니다.", "jp": "存在します。", "cn": "已存在。"},
            "pop_remove_group_title": {"en": "Remove", "kr": "삭제", "jp": "削除", "cn": "删除"},
            "pop_remove_group_msg": {"en": "Remove '{}'?", "kr": "'{}' 삭제?", "jp": "'{}' 削除？", "cn": "删除 '{}'?"},
            "pop_rename_group_title": {"en": "Rename", "kr": "이름변경", "jp": "名前変更", "cn": "重命名"},
            "pop_rename_group_label": {"en": "New Name:", "kr": "새 이름:", "jp": "新名前:", "cn": "新名称:"},
            "pop_rename_fail": {"en": "Failed.", "kr": "실패.", "jp": "失敗。", "cn": "失败。"},
            "pop_assign_select_group": {"en": "Select Group.", "kr": "그룹 선택.", "jp": "G選択。", "cn": "选组。"},
            "pop_assign_select_bones": {"en": "Select Bones.", "kr": "본 선택.", "jp": "ボーン 선택.", "cn": "选骨骼。"},
            "pop_find_bone_select_vert": {"en": "Select Verts.", "kr": "버텍스 선택.", "jp": "頂点選択。", "cn": "选顶点。"},
            "pop_find_bone_none": {"en": "None.", "kr": "없음.", "jp": "なし。", "cn": "无。"},
            "pop_transfer_select_source": {"en": "Select 1 Bone.", "kr": "본 1개 선택.", "jp": "ボーン1つ。",
                                           "cn": "选1个骨骼。"},
            "pop_transfer_select_verts": {"en": "Select Verts.", "kr": "버텍스 선택.", "jp": "頂点選択。", "cn": "选顶点。"},
            "pop_transfer_select_target_title": {"en": "Target", "kr": "타겟", "jp": "ターゲット", "cn": "目标"},
            "pop_transfer_select_target_label": {"en": "To:", "kr": "대상:", "jp": "先:", "cn": "至:"},
            "pop_transfer_no_change": {"en": "No change.", "kr": "변경 없음.", "jp": "変更なし。", "cn": "无变化。"},
            "msg_save_skin_confirm": {"en": "Save?", "kr": "저장하시겠습니까?", "jp": "保存？", "cn": "保存？"},
            "msg_bnlist_saved": {"en": "Saved: {}", "kr": "저장됨: {}", "jp": "保存: {}", "cn": "已保存: {}"},
            "msg_bnlist_loaded": {"en": "Loaded {} bones.", "kr": "{}개 본 로드됨.", "jp": "{} 読込。",
                                  "cn": "加载 {} 骨骼。"},
            "msg_import_warn": {"en": "Overwrite?", "kr": "덮어쓰시겠습니까?", "jp": "上書き？", "cn": "覆盖？"},
            "title_selection_error": {"en": "Error", "kr": "오류", "jp": "エラー", "cn": "错误"},
            "msg_selection_error": {"en": "Select Object.", "kr": "오브젝트 선택.", "jp": "Obj選択。", "cn": "选对象。"},
            "view_default": {"en": "Default View", "kr": "기본 보기", "jp": "デフォルト", "cn": "默认视图"},
            "view_hierarchy": {"en": "Hierarchy", "kr": "계층 구조", "jp": "階層", "cn": "层级"},
            "view_scene_layer": {"en": "Scene Layer", "kr": "씬 레이어", "jp": "シーン層", "cn": "场景图层"},
            "view_custom": {"en": "Custom Groups", "kr": "커스텀 그룹", "jp": "カスタムG", "cn": "自定义组"}
        }

    def set_language(self, code: str):
        if code in ["en", "kr", "jp", "cn"]:
            self.current_lang = code

    def get(self, key: str) -> str:
        return self.translations.get(key, {}).get(self.current_lang, f"<{key}>")


translator = Translator()